name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      dataform_changed: ${{ steps.filter.outputs.dataform }}
      datafusion_changed: ${{ steps.filter.outputs.datafusion }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dataform:
            - 'definitions/**'
            - 'includes/**'
            - 'workflow_settings.yaml'

  deploy-to-dev:
    needs: check-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: dataform-datafusion-dev
          service_account_key: ${{ secrets.DEV_SA_KEY }}
      - name: Install dependencies
        run: |
          npm install -g @dataform/cli
      - name: Deploy Dataform configs
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.DEV_SA_KEY }}
          DF_CREDENTIALS: ${{ secrets.DF_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > service-account.json
          cd dataform-project
          echo "$DF_CREDENTIALS" > .df-credentials.json
          dataform compile
          dataform run
