name: Develop CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: dataform-datafusion-dev
        service_account_key: ${{ secrets.DEV_SA_KEY }}
    - name: Deploy Dataform configs
      run: |
        npm i -g @dataform/cli
        cd dataform-project
        dataform compile
        dataform run